export const config = {
    message:{
        name:'*Please enter the name',
        address: "*Please enter the address.",
        validName: '*Please add  valid name.',
        lastName:'*Please enter the last name',
        validLastName: '*Please add more than 2 characters long.',
        userName: '*Please enter the username',
        userNameRegex:'*Please enter valid username. Eg:john_doe, user123, john-doe, etc.',
        date:'*Please update DOB',
        validDate:'*Age should be more than 18',
        validDate1:'*Age should not be more than 100',
        year:"*Year must be 4 digits",
        futureDate: "*Birth date cannot be in the future.",
        email:'*Please enter the email',
        validEmail:'*Please update valid email address',
        password:'*Please enter the password',
        confirmpassword:'*Please re-enter the password',
        validpassword: "*Password must be 8+ chars, 1 uppercase, 1 number, 1 special char.",
        matchPass:'*Password do not match',
        matchconfirmPass:'*Password do not match',
        mobile:"*Please enter the mobile number",
        validMobile:'*Please enter valid mobile number.',
        validAddress: '*Address should be 10 characters long in the address',
        addressLimit:"*Address should not be more than 100 characters.",
        errorMessage:'*Invalid email or password',
        credentialError: '*Username or Email already exists. Please use different credentials.',
        incompleteFormSubmission:"*Please fix the errors before submitting the form.",
        textTask:"*Task must be at least 3 characters long.",
        loginEmail:'*Please enter registered email address.',
        loginPassword: '*Please enter registered email address password.',
        taskExist: "*This task already exists.",
        userExists: "User already exists!",
        noAccount:"If you do not have an account",
        newAccount:"Create an Account",
        haveAccount:"If you have an account",
        account:"Login to your Account",
        welcome:"Welcome to the Dashboard",
        noTask:"No Tasks Found",
        invalid: "Invalid Input",
        alphabets: "Alphabets not allowed", 
        notBeZero:"Can't be zero",
        getItemLocalStorage:"Error getting item from localStorage: ",
        setItemLocalStorage: "Error setting item in localStorage: ",
        removeItemLocalStorage: "Error removing item from localStorage: "
    }, 
    Regex:{
        nameRegex:/^(?!.*\d)(?!.*\s\s)[a-zA-Z]+(?:\s[a-zA-Z]+)*$/,
        emailRegex: /^(?!.*\s)(?!.*[@]{2,})(?!.*\.\..*)(?!.*[#&+-])[a-z0-9.%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/,
        mobileRegex:/^\d{10}$/,
        passwordRegex:/^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])\S{8,}$/,
        dateRegex: /(dd|mm|yyyy)/i,
        taskRegex: /^[a-zA-Z0-9 ]{3,}$/,
        a:/[+\-*/%]{2,}/,
        b:/[+\-*%^/()=]/,
        c: /[+\-*/%]/,
        dots: /(^\.+|\.+$|\.{2,})/,
        alphabet: /[A-Za-z]/,
        expression1:/([+-])0\.\+/g,
        expression2:/([+-])0\.-/g,
        noZero:/\/\s*0(\.0*)?$/,
        valRegex:/^0+(?=[1-9])/,
        valRegex1:/(?<=[+\-*/])(0+)(?=[1-9][0-9]*)/,
        removeOperator: /[*+/-]$/,
        operatorCheck:/[+\-*/]/,
        operatorMatch:/[+\-*/]/g,
        dataStr:/[+\-*/]$/,
        checkDataStr:/\s*1\/100\s*$/,
        percentVal:/%/g,
        operatorStartWith:/[+\-*/%]/g,
        endWithOperator: /[+\-*/%]$/,
    },
}